# The URL the site will be built for
base_url = "https://spira.pages.dev"

# Site title — available in templates as {{ config.title }}
title = "Spira"

# Site description — available in templates as {{ config.description }}
description = "Din guide till krukväxternas vackra värld — lär dig odla, ta hand om och älska dina gröna vänner."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_filenames = ["rss.xml"]

default_language = "sv"
minify_html = false

[[taxonomies]]
name = "tags"
url = "tags"
feed = false

[markdown]
lazy_async_image = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author = "Spira"
